services:
  - type: web
    name: playlist-player
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main