services:
  - type: web
    name: playlist-player
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromService:
          type: pserv
          name: mongodb
          property: connectionString
      - key: NEXTAUTH_URL
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: YOUTUBE_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    domains:
      - playlist-player.onrender.com
    autoDeploy: true
    branch: main
    rootDir: ./
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - next.config.ts
        - tsconfig.json
        - tailwind.config.ts
        - postcss.config.mjs
        - components.json
        - eslint.config.mjs
      ignoredPaths:
        - .env*
        - README.md
        - .git/**
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html